### ISSUE TITLE
Add a GitHub Action to tag an existing container image

### ISSUE THREAD

**Issue by overheadhunter** [cryptomator/hub#113]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/hub/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/hub/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Add a manually dispatched workflow, that allows adding a tag (e.g. `latest`) to an existing image.

### Motivation

While we automatically publish container images when pushing git tags, we want manual control over which image is being considered the "latest" stable version.

Besides "latest", we might want to add further rolling tags such as "beta" in the future.

**Comment by infeo** [comment]
Implementation complete with https://github.com/cryptomator/hub/commit/495dcd4b13a87596953c47ef6a937d30e3d02415
