### ISSUE TITLE
Add Update-Check

### ISSUE THREAD

**Issue by infeo** [cryptomator/hub#119]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/hub/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/hub/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Add an update-check including a UI indicator for hub.

### Motivation

Prevent usage of outdated software.

### Considered Alternatives

-/-

### Anything else?

DoD:
* Hub instance checks regularly for updates
* If update is available, display it in hub frontend.

**Comment by overheadhunter** [comment]
I added [this proxy](https://api.cryptomator.org/updates/hub.json), which performs caching, logging and adds CORS headers, so we can poll this from our web frontend.
