### ISSUE TITLE
Add floating tags

### ISSUE THREAD

**Issue by overheadhunter** [cryptomator/hub#120]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/hub/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/hub/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

During tagged builds, add tags `stable` and `beta` depending on the git tag

### Motivation

It's a best practice to make sure the latest stable (or beta) version is used downstream.

**Comment by tobihagemann** [comment]
Should we consider the following edge case?

1. Latest `stable` is `1.1.0`.
2. New Hotfix `1.0.5` is being tagged.

Will `1.1.0` stay as `stable`?
- If yes, this will require more logic but it should be doable.
- If not, the workaround is to just re-tag `stable` manually afterwards. (This requires specific knowledge.)

Apart from that, what is the difference between `latest` and `stable`?

**Comment by overheadhunter** [comment]
> Will `1.1.0` stay as `stable`?
> 
> * If yes, this will require more logic but it should be doable.

Preferably. But good point, not sure how to do this.



> Apart from that, what is the difference between `latest` and `stable`?

`latest` is just the most recent build (neither needs to be stable nor based on a newer commit than any other tag). See [this blog post](https://medium.com/@mccode/the-misunderstood-docker-tag-latest-af3babfd6375).

**Comment by overheadhunter** [comment]
For now, we tag manually. Let's create a new issue if we want to change this.
