### ISSUE TITLE
Close dropdown in navbar after clicking on item

### ISSUE THREAD

**Issue by tobihagemann** [cryptomator/hub#123]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/hub/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/hub/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Profile dropdown menu (navbar) doesn't close after clicking on an item inside it.

### System Setup

```markdown
- Hub: 1.0.0-beta1
```

### Steps to Reproduce

1. Open profile dropdown in navbar
2. Click on any item (e.g., "Settings")

### Expected Behavior

Browser navigates to clicked item and closes dropdown menu.

### Actual Behavior

Browser navigates to clicked item but doesn't close dropdown menu.

### Reproducibility

Always

**Comment by SailReal** [comment]
Implemented in https://github.com/cryptomator/hub/commit/b1b4430b8c8c7adf28399b547215b041da7f0284
