### ISSUE TITLE
Incorrect Redirect after Login from Device

### ISSUE THREAD

**Issue by overheadhunter** [cryptomator/hub#127]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/hub/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/hub/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

`vault.cryptomator` contains incorrect URLs

### System Setup

```markdown
- Hub: 1.0.0-beta2
- Keycloak: 19.0.1
- Cryptomator (Desktop/Android/iOS): 1.6.13
```

### Steps to Reproduce

1. Create & Download new Vault
2. Try to unlock / register device

### Expected Behavior

After successful OAuth, the browser redirects to `hub.example.com/app/unlock-success?...`.

### Actual Behavior

After successful OAuth, the browser redirects to `hub.example.com/appunlock-success?...`.

### Reproducibility

Always

### Relevant Log Output

```shell
// excerpt from decoded vault.cryptomator:

  "hub": {
    "clientId": "cryptomatorhub",
    "authEndpoint": "https://hub.example.com/kc/realms/cryptomator/protocol/openid-connect/auth",
    "tokenEndpoint": "https://hub.example.com/kc/realms/cryptomator/protocol/openid-connect/token",
    "devicesResourceUrl": "https://hub.example.com/api/devices/",
    "authSuccessUrl": "https://hub.example.com/appunlock-success?vault=233d4b89-5877-41ed-8615-4852f3e9e72f",
    "authErrorUrl": "https://hub.example.com/appunlock-error?vault=233d4b89-5877-41ed-8615-4852f3e9e72f"
  }
```

### Anything else?

Unlock is successful, just the redirect fails.

**Comment by infeo** [comment]
Fixed in 576011be8a11392376d9a04e6761bc32ab250d6c
