### ISSUE TITLE
Role "user" is missing in `realm.json`

### ISSUE THREAD

**Issue by overheadhunter** [cryptomator/hub#142]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/hub/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/hub/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Importing a realm.json created by the setup wizard misses role "user"

### System Setup

```markdown
- Keycloak: 19.0.1
```

### Steps to Reproduce

1. Launch a new Keycloak instance
2. Visit the [Setup Wizard](https://cryptomator.org/hub/setup)
3. Check box saying "Use an existing Keycloak installation"
4. Copy the `realm.json`
5. Log into the Keycloak Admin UI
6. Click "Create Realm" and paste the json
7. On the newly created realm, go to Realm Settings and in the upper right corner click on Actions → Partial Import
8. Paste the json again, because Keycloak is stupid and ignored half the file during Realm Creation
9. Check all the boxes below to import Users, Clients and Realm Roles.

### Expected Behavior

Import works the same as with `kc.sh --import-realm`, ideally during realm creation

### Actual Behavior

Error popover saying:

> Import failed: Unable to find composite realm role: user

### Reproducibility

Always

### Anything else?

Adding the missing role fixes the issue, however we assumed this to be a pre-defined role. Furthermore we can not tell, why it works with `--import-realm`.

```json
{
    "name": "user",
    "description": "User",
    "composite": false
}
```

**Comment by SailReal** [comment]
@overheadhunter see the second (and closing) commit

**Comment by overheadhunter** [comment]
Somehow missed that, despite looking for it. Sorry!
