### ISSUE TITLE
admin user needs realm management roles

### ISSUE THREAD

**Issue by overheadhunter** [cryptomator/hub#155]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/hub/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/hub/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

The setup wizard should make sure that the initial user has sufficient privileges to manage the realm

### System Setup

```markdown
- realm.json created for Hub 1.0.0-beta5
```

### Steps to Reproduce

1. Try to log into keycloak admin console not using the server admin user but rather the realm admin

### Expected Behavior

You are logged in and can manage your own realm (but can not see other realms)

### Actual Behavior

Error 403

### Reproducibility

Always

### Anything else?

Related to #107

**Comment by overheadhunter** [comment]
fixed in https://github.com/cryptomator/cryptomator.github.io/commit/cc014b1ae135630905e5867df06f953048faaaf1

**Comment by SailReal** [comment]
@overheadhunter we need to fix it in https://github.com/cryptomator/hub/blob/c39b1e204a0a9a106b1607ee154897eff2fbedd0/backend/src/main/resources/dev-realm.json#L19-L28 too.

**Comment by overheadhunter** [comment]
dev-realm is only relevant during `quarkus:dev`, where we only have a global admin user anyway.

**Comment by SailReal** [comment]
Okay but on my device, running the latest state of the release/1.0.0-branch using `quarkus:dev`, I get a 403 when clicking on the admin link in Hub:
![Screenshot from 2022-09-28 13-27-43](https://user-images.githubusercontent.com/1786772/192768123-e6298674-5cb8-4a82-bcf3-668fca137dad.png)

If I grant the admin user the realm-roles, the link works as expected.

**Comment by overheadhunter** [comment]
ohhhhhhh my bad, I thought it would be the "other" admin user being used here.

**Comment by SailReal** [comment]
Works now :+1:
