### ISSUE TITLE
Admin can't see all vaults, if she doesn't have access to at least one vault

### ISSUE THREAD

**Issue by overheadhunter** [cryptomator/hub#159]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/hub/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/hub/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

When not having access to at least one vault, the vault list only shows the "create new vault" option, despite being admin

### System Setup

```markdown
- Hub: 1.0.0-beta6
- Keycloak: 19.0.2
```

### Steps to Reproduce

1. On a clean setup, create a new vault as a non-admin user
2. Switch to admin user
3. Go to Vault list

### Expected Behavior

<img width="1095" alt="Screenshot 2022-09-28 at 17 20 17" src="https://user-images.githubusercontent.com/1204330/192819138-e6adca99-866a-4a4a-ab2c-6ad3826d5071.png">

### Actual Behavior

<img width="534" alt="Screenshot 2022-09-28 at 17 20 55" src="https://user-images.githubusercontent.com/1204330/192819094-cc586ad1-34c7-45d9-be3d-c8415a7b5e3d.png">

### Reproducibility

Always

### Anything else?

Related to #106

**Comment by SailReal** [comment]
Fixed in https://github.com/cryptomator/hub/pull/160
