### ISSUE TITLE
Unlock success screen shows "unknown device" even if device is registered

### ISSUE THREAD

**Issue by infeo** [cryptomator/hub#163]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/hub/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/hub/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

After registering a device for a vault, the unlock success screen

### System Setup

```markdown
- Hub: 1.0.0-beta5
- Keycloak: 19.0.0
- Cryptomator (Desktop/Android/iOS): 1.6.14
```

### Steps to Reproduce

1. Register a deivce with desktop app
2. Give device permissions to access
3. Unlock vault

### Expected Behavior

The webpage says device known or something similar

### Actual Behavior

The webpage says device UNKNOWN.

### Reproducibility

Always

### Relevant Log Output

```shell
-/-
```

### Anything else?

https://user-images.githubusercontent.com/9036915/194040872-7c200191-1158-48cc-adc5-6c9deaccd97c.mp4

**Comment by SailReal** [comment]
Fixed in https://github.com/cryptomator/hub/commit/97633f8107955ea0106c2844695bf9e6cc651087
