### ISSUE TITLE
Verify Trust Level During Access Grant

### ISSUE THREAD

**Issue by overheadhunter** [cryptomator/hub#191]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/hub/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/hub/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Visualize trust level of users when granting access

### Motivation

As a vault owner, I want to be sure not to accidentally grant access to some untrusted user. Once we implemented #190, it is possible to show different trust levels and display a warning if trying to grant access to an unknown party.

### Anything else?

Trust levels could be:

1. _ultimate_, if a public key is signed by the vault owner herself
2. _good_, if there is a chain of signatures from the given public key leading to vault owner
3. _low_, otherwise

**Comment by SailReal** [comment]
@overheadhunter this is also somehow implemented in https://github.com/cryptomator/hub/pull/281, should we close this issue as well, or keep it open for UI enhancements?

**Comment by overheadhunter** [comment]
we decided to do further UI enhancements on demand
