### ISSUE TITLE
Promote Vault Members to Owners

### ISSUE THREAD

**Issue by overheadhunter** [cryptomator/hub#214]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/hub/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/hub/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

As a vault owner I want to change the role of other members

### Motivation

After the #209 refactoring there is no other option to have multiple owners. Multiple owners are required, as a single owner might not be available at all time.

### Anything else?

The backend already accepts `PUT /{vaultId}/users/{userId}/?role=OWNER` and `PUT /{vaultId}/groups/{groupId}/?role=OWNER`~~, however it does not distinguish between create and update requests yet (always returns 201). Not sure if this should be changed~~.

**Comment by tobihagemann** [comment]
Fixed in #211.
