### ISSUE TITLE
Recovering vaults after resetting my account

### ISSUE THREAD

**Issue by SailReal** [cryptomator/hub#237]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/hub/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/hub/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

As a owner of a vault, I would like to be able to recover it after resetting my account key

### System Setup

```markdown
- Hub: `commit-148e820af7644132ded9e4297ac0c9589b473343-amd64`
```

### Steps to Reproduce

1. Create vault asd with user admin
2. Open another browser and login as admin
3. Execute `Reset my account` introduced in https://github.com/cryptomator/hub/issues/208
4. Open vault details of asd

### Expected Behavior

Hub informs me about how can I recover access to the selected vault:

* When I'm the only owner, Hub needs to ask for my recovery key to recover this vault
* When I'm not the only owner, I can enter my recovery key or get the information to wait until an other owner clicks "Update Permission"

### Actual Behavior

Hub looks quiet normal beside the fact that the member list is empty and every change to that vault results in a `Unexpected Error: Insufficient rights to access resource`

![image](https://github.com/cryptomator/hub/assets/1786772/88756660-acfc-4570-91db-f4d786874c97)

### Reproducibility

Always

**Comment by overheadhunter** [comment]
I guess the problem is that the "vault detail view" assumes you have an access token for this vault. However resetting an account will delete those.

So if you have owner privileges but not a token, we might need to prompt for the recovery key before continuing to the vault detail view, right?

**Comment by SailReal** [comment]
Exactly, that's what I guess as well.

The remaining question is if we should handle one and multiple vault owners with access tokens differently or always show the recover vault dialog like mentioned in the report 

> ### Expected Behavior
> 
> Hub informs me about how can I recover access to the selected vault:
> 
> * When I'm the only owner, Hub needs to ask for my recovery key to recover this vault
> * When I'm not the only owner, I can enter my recovery key or get the information to wait until an other owner clicks "Update Permission"

**Comment by overheadhunter** [comment]
To keep it simple, let's start with always prompting for the recovery key. Then re-encrypt the vault key for the user's new private key. All remaining users should remain untouched.

It can be a future refinement to add some "Alternatively, ask Alice" text to said prompt.
